// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/proto/recharge_log.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRechargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRechargeRequest) Reset() {
	*x = CreateRechargeRequest{}
	mi := &file_api_proto_recharge_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRechargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRechargeRequest) ProtoMessage() {}

func (x *CreateRechargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_recharge_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRechargeRequest.ProtoReflect.Descriptor instead.
func (*CreateRechargeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_recharge_log_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRechargeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateRechargeRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateRechargeRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type RechargeLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RechargeId    string                 `protobuf:"bytes,1,opt,name=recharge_id,json=rechargeId,proto3" json:"recharge_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserNickname  string                 `protobuf:"bytes,3,opt,name=user_nickname,json=userNickname,proto3" json:"user_nickname,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Remark        string                 `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeLogResponse) Reset() {
	*x = RechargeLogResponse{}
	mi := &file_api_proto_recharge_log_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeLogResponse) ProtoMessage() {}

func (x *RechargeLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_recharge_log_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeLogResponse.ProtoReflect.Descriptor instead.
func (*RechargeLogResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_recharge_log_proto_rawDescGZIP(), []int{1}
}

func (x *RechargeLogResponse) GetRechargeId() string {
	if x != nil {
		return x.RechargeId
	}
	return ""
}

func (x *RechargeLogResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RechargeLogResponse) GetUserNickname() string {
	if x != nil {
		return x.UserNickname
	}
	return ""
}

func (x *RechargeLogResponse) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RechargeLogResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RechargeLogResponse) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

var File_api_proto_recharge_log_proto protoreflect.FileDescriptor

const file_api_proto_recharge_log_proto_rawDesc = "" +
	"\n" +
	"\x1capi/proto/recharge_log.proto\x12\x03api\"`\n" +
	"\x15CreateRechargeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"\xc3\x01\n" +
	"\x13RechargeLogResponse\x12\x1f\n" +
	"\vrecharge_id\x18\x01 \x01(\tR\n" +
	"rechargeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\ruser_nickname\x18\x03 \x01(\tR\fuserNickname\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06remark\x18\x06 \x01(\tR\x06remark2\xaf\x01\n" +
	"\x12RechargeLogService\x12I\n" +
	"\x11CreateRechargeLog\x12\x1a.api.CreateRechargeRequest\x1a\x18.api.RechargeLogResponse\x12N\n" +
	"\x12StreamRechargeLogs\x12\x1a.api.CreateRechargeRequest\x1a\x18.api.RechargeLogResponse(\x010\x01B\x1eZ\x1cbackend-onboarding/api/protob\x06proto3"

var (
	file_api_proto_recharge_log_proto_rawDescOnce sync.Once
	file_api_proto_recharge_log_proto_rawDescData []byte
)

func file_api_proto_recharge_log_proto_rawDescGZIP() []byte {
	file_api_proto_recharge_log_proto_rawDescOnce.Do(func() {
		file_api_proto_recharge_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_recharge_log_proto_rawDesc), len(file_api_proto_recharge_log_proto_rawDesc)))
	})
	return file_api_proto_recharge_log_proto_rawDescData
}

var file_api_proto_recharge_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_recharge_log_proto_goTypes = []any{
	(*CreateRechargeRequest)(nil), // 0: api.CreateRechargeRequest
	(*RechargeLogResponse)(nil),   // 1: api.RechargeLogResponse
}
var file_api_proto_recharge_log_proto_depIdxs = []int32{
	0, // 0: api.RechargeLogService.CreateRechargeLog:input_type -> api.CreateRechargeRequest
	0, // 1: api.RechargeLogService.StreamRechargeLogs:input_type -> api.CreateRechargeRequest
	1, // 2: api.RechargeLogService.CreateRechargeLog:output_type -> api.RechargeLogResponse
	1, // 3: api.RechargeLogService.StreamRechargeLogs:output_type -> api.RechargeLogResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_recharge_log_proto_init() }
func file_api_proto_recharge_log_proto_init() {
	if File_api_proto_recharge_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_recharge_log_proto_rawDesc), len(file_api_proto_recharge_log_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_recharge_log_proto_goTypes,
		DependencyIndexes: file_api_proto_recharge_log_proto_depIdxs,
		MessageInfos:      file_api_proto_recharge_log_proto_msgTypes,
	}.Build()
	File_api_proto_recharge_log_proto = out.File
	file_api_proto_recharge_log_proto_goTypes = nil
	file_api_proto_recharge_log_proto_depIdxs = nil
}
