// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/proto/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_proto_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UserIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"` // input: list of IDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIdsRequest) Reset() {
	*x = UserIdsRequest{}
	mi := &file_api_proto_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIdsRequest) ProtoMessage() {}

func (x *UserIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIdsRequest.ProtoReflect.Descriptor instead.
func (*UserIdsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserIdsRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_api_proto_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

var File_api_proto_user_proto protoreflect.FileDescriptor

const file_api_proto_user_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/user.proto\x12\x03api\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"+\n" +
	"\x0eUserIdsRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"C\n" +
	"\fUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname2\x80\x01\n" +
	"\vUserService\x125\n" +
	"\vGetUserById\x12\x13.api.GetUserRequest\x1a\x11.api.UserResponse\x12:\n" +
	"\x0eGetUsersStream\x12\x13.api.UserIdsRequest\x1a\x11.api.UserResponse0\x01B\x1eZ\x1cbackend-onboarding/api/protob\x06proto3"

var (
	file_api_proto_user_proto_rawDescOnce sync.Once
	file_api_proto_user_proto_rawDescData []byte
)

func file_api_proto_user_proto_rawDescGZIP() []byte {
	file_api_proto_user_proto_rawDescOnce.Do(func() {
		file_api_proto_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_user_proto_rawDesc), len(file_api_proto_user_proto_rawDesc)))
	})
	return file_api_proto_user_proto_rawDescData
}

var file_api_proto_user_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_user_proto_goTypes = []any{
	(*GetUserRequest)(nil), // 0: api.GetUserRequest
	(*UserIdsRequest)(nil), // 1: api.UserIdsRequest
	(*UserResponse)(nil),   // 2: api.UserResponse
}
var file_api_proto_user_proto_depIdxs = []int32{
	0, // 0: api.UserService.GetUserById:input_type -> api.GetUserRequest
	1, // 1: api.UserService.GetUsersStream:input_type -> api.UserIdsRequest
	2, // 2: api.UserService.GetUserById:output_type -> api.UserResponse
	2, // 3: api.UserService.GetUsersStream:output_type -> api.UserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_user_proto_init() }
func file_api_proto_user_proto_init() {
	if File_api_proto_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_user_proto_rawDesc), len(file_api_proto_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_user_proto_goTypes,
		DependencyIndexes: file_api_proto_user_proto_depIdxs,
		MessageInfos:      file_api_proto_user_proto_msgTypes,
	}.Build()
	File_api_proto_user_proto = out.File
	file_api_proto_user_proto_goTypes = nil
	file_api_proto_user_proto_depIdxs = nil
}
