// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/dao/internal"
)

// internalRechargeLogDao is an internal type for wrapping the internal DAO implementation.
type internalRechargeLogDao = *internal.RechargeLogDao

// rechargeLogDao is the data access object for the table recharge_log.
// You can define custom methods on it to extend its functionality as needed.
type rechargeLogDao struct {
	internalRechargeLogDao
}

var (
	// RechargeLog is a globally accessible object for table recharge_log operations.
	RechargeLog = rechargeLogDao{
		internal.NewRechargeLogDao(),
	}
)

// Add your custom methods and functionality below.
